package com.foodplanner.controller;

import com.foodplanner.model.*;
import com.foodplanner.service.FirebaseService;
import com.foodplanner.service.MenuService;
import com.foodplanner.service.StoreOfferService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.core.user.OAuth2User;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.util.*;

@Controller
@RequestMapping("/menu")
public class MenuController {

    private static final Logger log = LoggerFactory.getLogger(MenuController.class);

    private final MenuService menuService;
    private final FirebaseService firebaseService;
    private final StoreOfferService storeOfferService;

    public MenuController(MenuService menuService,
                          FirebaseService firebaseService,
                          StoreOfferService storeOfferService) {
        this.menuService = menuService;
        this.firebaseService = firebaseService;
        this.storeOfferService = storeOfferService;
    }

    @GetMapping
    public String weeklyMenu(@AuthenticationPrincipal OAuth2User principal,
                              @RequestParam(required = false) String weekId,
                              Model model) {
        String userId = principal.getAttribute("sub");
        User user = firebaseService.getUser(userId);
        MenuConfig config = user != null && user.getMenuConfig() != null
                ? user.getMenuConfig() : new MenuConfig();

        boolean isCurrentWeek = (weekId == null);
        String targetWeekId = weekId != null ? weekId : menuService.getCurrentWeekId();
        model.addAttribute("weekId", targetWeekId);
        model.addAttribute("prevWeekId", menuService.getPreviousWeekId(targetWeekId));
        model.addAttribute("nextWeekId", menuService.getNextWeekIdFrom(targetWeekId));
        model.addAttribute("currentWeekId", menuService.getCurrentWeekId());

        WeeklyMenu menu = menuService.getWeekMenu(userId, targetWeekId);

        // Auto-generate if viewing the current week and no menu exists yet
        if (menu == null && isCurrentWeek) {
            try {
                menu = menuService.generateAndSaveWeeklyMenuForWeek(userId, targetWeekId, null);
                model.addAttribute("autoGenerated", true);
            } catch (Exception e) {
                log.warn("Auto-generation failed for week {}: {}", targetWeekId, e.getMessage());
            }
        }

        model.addAttribute("menu", menu);
        model.addAttribute("user", user);
        model.addAttribute("days", menuService.getMenuDays(config));
        model.addAttribute("savedWeekIds", menuService.listMenuWeekIds(userId));

        // Load recipes for meals that have a recipeId
        Map<String, Recipe> recipeMap = new HashMap<>();
        if (menu != null && menu.getDays() != null) {
            for (WeeklyMenu.DayMenu dayMenu : menu.getDays().values()) {
                loadRecipesFromMeals(userId, recipeMap, dayMenu.getDinner());
                loadRecipesFromMeals(userId, recipeMap, dayMenu.getLunch());
                loadRecipesFromMeals(userId, recipeMap, dayMenu.getBreakfast());
            }
        }
        model.addAttribute("recipes", recipeMap);

        return "menu/weekly";
    }

    private void loadRecipesFromMeals(String userId, Map<String, Recipe> recipeMap,
                                       List<WeeklyMenu.PlannedMeal> meals) {
        if (meals == null) return;
        for (WeeklyMenu.PlannedMeal meal : meals) {
            if (meal.getRecipeId() != null && !recipeMap.containsKey(meal.getRecipeId())) {
                try {
                    Recipe recipe = firebaseService.getRecipe(userId, meal.getRecipeId());
                    if (recipe != null) recipeMap.put(meal.getRecipeId(), recipe);
                } catch (Exception e) {
                    log.debug("Could not load recipe {}: {}", meal.getRecipeId(), e.getMessage());
                }
            }
        }
    }

    @PostMapping("/generate")
    public String generateMenu(@AuthenticationPrincipal OAuth2User principal, Model model) {
        String userId = principal.getAttribute("sub");
        try {
            WeeklyMenu menu = menuService.generateAndSaveWeeklyMenu(userId);
            return "redirect:/menu?weekId=" + menu.getWeekId() + "&generated=true";
        } catch (Exception e) {
            model.addAttribute("error", "Failed to generate menu: " + e.getMessage());
            return "redirect:/menu?error=true";
        }
    }

    @PostMapping("/{weekId}/regenerate")
    public String regenerateMenu(@AuthenticationPrincipal OAuth2User principal,
                                  @PathVariable String weekId,
                                  @RequestParam(required = false) String feedback) {
        String userId = principal.getAttribute("sub");
        try {
            menuService.generateAndSaveWeeklyMenuForWeek(userId, weekId, feedback);
            return "redirect:/menu?weekId=" + weekId + "&generated=true";
        } catch (Exception e) {
            log.error("Failed to regenerate menu for week {}", weekId, e);
            return "redirect:/menu?weekId=" + weekId + "&error=true";
        }
    }

    @PostMapping("/{weekId}/meal/{day}/{mealType}/{mealIndex}/regenerate")
    public String regenerateDish(@AuthenticationPrincipal OAuth2User principal,
                                  @PathVariable String weekId,
                                  @PathVariable String day,
                                  @PathVariable String mealType,
                                  @PathVariable int mealIndex,
                                  @RequestParam(required = false) String feedback) {
        String userId = principal.getAttribute("sub");
        try {
            menuService.regenerateDish(userId, weekId, day, mealType, mealIndex, feedback);
            return "redirect:/menu?weekId=" + weekId;
        } catch (Exception e) {
            log.error("Failed to regenerate dish", e);
            return "redirect:/menu?weekId=" + weekId + "&error=true";
        }
    }

    @GetMapping("/config")
    public String menuConfig(@AuthenticationPrincipal OAuth2User principal, Model model) {
        String userId = principal.getAttribute("sub");
        User user = firebaseService.getUser(userId);
        MenuConfig config = user != null && user.getMenuConfig() != null
                ? user.getMenuConfig() : new MenuConfig();
        model.addAttribute("config", config);
        model.addAttribute("availableStores", storeOfferService.getAvailableStores());
        List<Store> selectedStores = user != null && user.getSelectedStores() != null
                ? user.getSelectedStores() : List.of();
        model.addAttribute("selectedStores", selectedStores);
        return "menu/config";
    }

    @PostMapping("/config")
    public String saveMenuConfig(@AuthenticationPrincipal OAuth2User principal,
                                  @ModelAttribute MenuConfig config,
                                  @RequestParam(required = false) List<String> selectedStores) {
        String userId = principal.getAttribute("sub");
        firebaseService.saveMenuConfig(userId, config);
        List<Store> stores = new ArrayList<>();
        Set<String> seenIds = new LinkedHashSet<>();
        if (selectedStores != null) {
            for (String entry : selectedStores) {
                // format: "id|name|chain"
                String[] parts = entry.split("\\|", 3);
                if (parts.length == 3 && !parts[0].isBlank() && seenIds.add(parts[0])) {
                    stores.add(new Store(parts[0], parts[1], parts[2]));
                }
            }
        }
        firebaseService.saveSelectedStores(userId, stores);
        return "redirect:/menu/config?saved=true";
    }

    @PostMapping("/{weekId}/meal/{day}/{mealType}/{mealIndex}/complete")
    @ResponseBody
    public ResponseEntity<Map<String, Boolean>> toggleMealComplete(
            @AuthenticationPrincipal OAuth2User principal,
            @PathVariable String weekId,
            @PathVariable String day,
            @PathVariable String mealType,
            @PathVariable int mealIndex,
            @RequestParam boolean completed) {
        String userId = principal.getAttribute("sub");
        menuService.updateMealCompletion(userId, weekId, day, mealType, mealIndex, completed);
        return ResponseEntity.ok(Map.of("completed", completed));
    }
}
